{{- if .Values.monitoring.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: {{ .Values.monitoring.prometheus.image }}
          ports:
            - containerPort: {{ .Values.monitoring.prometheus.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - port: {{ .Values.monitoring.prometheus.port }}
      targetPort: {{ .Values.monitoring.prometheus.port }}
{{- end }}