- hosts: localhost
  vars:
    state: present        # present / absent
    replicas: 1           # backend replica 수

  tasks:
    - name: Deploy platform
      shell: |
        helm upgrade --install my-platform ../helm/my-platform \
        --set backend.replicaCount={{ replicas }} --wait
      when: state == "present"

    - name: Remove platform
      shell: helm uninstall my-platform
      when: state == "absent"